#!/bin/sh
set -eux

if [ "$#" -ne 1 ]
then
echo "no ref given; using master"
ref="master"
else
ref=$1
echo "building ref $1"
fi

ROOT=/var/ci
export PATH="$ROOT/rbenv/bin:$PATH"
export RBENV_ROOT=$ROOT/rbenv
eval "$($ROOT/rbenv/bin/rbenv init -)"

build_id=$(($(cd $ROOT/builds; ls | sort -n | tail -1) +1))
echo $build_id > $ROOT/last_build
build_dir=$ROOT/builds/$build_id

cd $ROOT/builds
echo "pruning old builds"
ls|sort -n|head -n -10 | xargs rm -fr

mkdir $build_dir

which ruby
ruby -v
bundle -v

cd $build_dir
keyfile=$(mktemp)
set +x
echo "$GITHUB_SSH_KEY" > $keyfile
set -x
ssh-agent bash -c 'ssh-add '$keyfile'; git clone git@github.com:'$REPO'.git .'
rm -f $keyfile
git reset --hard $ref

bin/qa-ci
